name: Docker build for main branch
on:
  push:
    branches:
      - 'ci'
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: dir
        run: pwd && ls      
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{ secrets.IMAGE }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: aevea/cache
          tag: latest
          build_file: /github/workspace/Dockerfile
          path:  /github/workspace
